//
// Created by Niraj on 12-07-2026.
//

#ifndef PONGARENA_GAMESTATES_H
#define PONGARENA_GAMESTATES_H

enum class GameStates
{
    STATE_MENU,
    STATE_CHAR_SELECT,
    STATE_GAMEOVER,
    STATE_SETTINGS,
    STATE_MODE_SELECTION,
    STATE_LOCAL_VIEW,
    STATE_AI_VIEW
};

#endif //PONGARENA_GAMESTATES_H
